version: '3.9'
services:
  sqldb:
    container_name: sqldb
    environment:
      SA_PASSWORD: Passw0rd!
      ACCEPT_EULA: Y
    restart: always
    volumes:
    - sqldb_data:/var/opt/mssql
    ports:
    - 1433:1433
  basketdb:
    container_name: basketdb
    restart: always
    ports:
    - 6379:6379
  inventorydb:
    container_name: inventorydb
    restart: always
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
  portainer:
    container_name: portainer
    restart: always
    ports:
    - 8080:8000
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
  elasticsearch:
    container_name: elasticsearch
    environment:
      xpack.monitoring.enabled: 'true'
      xpack.watcher.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    ports:
    - 9200:9200
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
    - elasticsearch
    ports:
    - 5601:5601
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=Server=sqldb;Database=ProductDb;User Id=sa;Password=Passw0rd!;Multipleactiveresultsets=true;"
    depends_on: 
      - sqldb
    ports:
      - "6002:80"
    restart: always
  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=Server=sqldb;Database=CustomerDb;User Id=sa;Password=Passw0rd!;Multipleactiveresultsets=true;"
    depends_on: 
      - sqldb
    ports:
      - "6003:80"
    restart: always
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "6004:80"
    restart: always
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=Server=sqldb;Database=OrderDb;User Id=sa;Password=Passw0rd!;Multipleactiveresultsets=true"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - sqldb
      - rabbitmq
    ports:
      - "6005:80"
    restart: always